### ISSUE TITLE
[Enhancement] I suggest you add the block command. 

### ISSUE THREAD

**Issue by HowToPlayMeow** [DosMike/TF2-DropWeapon#5]
I'm using your plugin on the jailbreak server and I ran into a problem where the red team threw away the "melee weapon", causing the red team to hold a "primary weapon" that had no ammo. It makes the Blue Team confused about whether it's the Rebellers or not.

I would like you to add the block slots command.
 **Example:** **"sm_tf2dropweapon_blockslots 3"**
  -1 Block Weapons Primary
  -2 Block Weapons Secondary
  -3 Block Weapons Melee
  -4 Block Weapons Construction PDA,Disguise Kit
  -5 Block Weapons Destruction PDA

and additional advice **"sm_tf2dropweapon_blockteams"**
Your plugin can only be used on some servers. But if you add "Block Teams" that prevents some teams from throwing weapons, you can use your plugin on other servers.
 **Example:** 
  -FF2
  -VSH
  -Zombies

**The reason I use your plugin on my jailbreak server? In spite of the problem that I told you already Because I really like your plugin, it's really cool.**

**Comment by DosMike** [comment]
Do you want a module plugin, specifically for gamemodes, otherwise it's not quite clear to me how that should work as a command. What exactly is your goal? Do you want to block dropping weapons from specific team/slot on demand (changed at any time), or constantly (throughout the map)?

**Comment by HowToPlayMeow** [comment]
I want your plugin to work in different game modes.

And what I want is a team/slot block weapon.

[throughout the map] I think it will be good.

**Comment by DosMike** [comment]
Just to make sure: You want to block dropping weapons from specific slots if on a certain team, for gamemodes.

This could be done with a addons/sourcemod/configs file as well, giving event more control. Maybe something like this?

```c
"DropWeapon"
{
    // slot -> permission string
    // so this would allow everyone to drop primary
    "primary" ""
    // and only generic admins to drop secondary
    "secondary" "a"
    // and with a special word, nobody to drop melee
    "melee" "nobody"
    // and maybe control per team like this
    "pda" {
        "red" "nobody"
        "blue" ""
    }
}
```

Or do you really want a command?

To clarify: this is a suggestion, not currently a feature

**Comment by HowToPlayMeow** [comment]
I think it's very good.

**Comment by DosMike** [comment]
Sorry it took so long, please open a new issue if you encounter any bugs with the new version

**Comment by HowToPlayMeow** [comment]
Thank you for the update.
