### ISSUE TITLE
Why can't I use it?

### ISSUE THREAD

**Issue by HowToPlayMeow** [DosMike/TF2-DropWeapon#6]
This is the setting I use.

	"DropWeapon"
	{
		"action_drop"
		{
			"Melee"
			{
				"red"		"nobody"
			}			
			"building"		"nobody"
		}
		"action_pickup"
		{
			"Melee"
			{
				"red"		"nobody"
			}
			"building"		"nobody"
		}
	}

It doesn't work or I have the wrong settings?

https://github.com/DosMike/TF2-DropWeapon/assets/124129630/3e847a87-06c6-4261-bc49-302cedf5da65

**Comment by DosMike** [comment]
please keep the names lowercase and tell me if that helps (melee specifically in this case)

**Comment by HowToPlayMeow** [comment]
I just had some free time to test it. It didn't work.

"DropWeapon"
  {
	  "action_drop"
	  {
		  "melee"
		  {
			  "red"		"nobody"
		  }			
		  "building"		"nobody"
	  }
	  "action_pickup"
	  {
		  "melee"
		  {
			  "red"		"nobody"
		  }
		  "building"		"nobody"
	  }
  }

**Comment by HowToPlayMeow** [comment]
I just had some free time to test it. It didn't work.

    "DropWeapon"
    {
        "action_drop"
        {
            "melee"
            {
                "red"		"nobody"
            }			
            "building"		"nobody"
        }
        "action_pickup"
        {
            "melee"
            {
                "red"		"nobody"
            }
            "building"		"nobody"
        }
    }

**Comment by DosMike** [comment]
Sorry it took so long, i got busy...
I somehow messed up config parsing, fixed it in a new release. (Compiled with latest sourcemod, i can compile with an older version if needed, just give me a heads up, if you get another error)
